¡Hola! 👋 Soy Bryan Chanca

Soy un estudiante de Ingeniería de Sistemas en la Universidad Nacional de Ingeniería (UNI), con una gran pasión por el mundo de los datos y su capacidad para transformar la toma de decisiones.

**Mi Enfoque:**

Actualmente, mi principal enfoque se centra en el **análisis de datos**. Me entusiasma explorar, limpiar, transformar y visualizar datos para extraer insights valiosos y comunicarlos de manera efectiva.

**Habilidades Clave:**

* **Lenguajes de Programación:** Python (Pandas, NumPy, Matplotlib, Seaborn), SQL
* **Herramientas de Visualización:** Power BI, Excel, Tableau (Conocimientos básicos)
* **Bases de Datos:** SQL Server
* **Metodologías:** Conocimientos básicos de ETL

**Lo que puedes encontrar en mi GitHub:**

En este espacio, iré compartiendo proyectos personales y académicos que reflejan mi aprendizaje y mis habilidades en el campo del análisis de datos. Aquí encontrarás desde análisis exploratorios hasta pequeñas aplicaciones y visualizaciones. ¡Estoy en constante aprendizaje y siempre buscando nuevos desafíos!

**Mi Objetivo:**

Busco oportunidades para aplicar y expandir mis habilidades en el mundo real, colaborando en proyectos desafiantes donde pueda contribuir con mi capacidad analítica y mi entusiasmo por aprender. ¡Estoy abierto a conectar con profesionales del sector y explorar nuevas posibilidades!

**¡Conéctate conmigo!**

* [Tu perfil de LinkedIn](https://www.linkedin.com/in/Bryanchanca)
* [Tu correo electrónico](bchancac@uni.pe)

¡Gracias por visitar mi perfil! 😊
